### ISSUE TITLE
No implementation found for method login on channel ec.dina/flutter_facebook_auth

### ISSUE THREAD

**Issue by juliano0365** [darwin-morocho/flutter-facebook-auth#11]
I'm trying to replicate the example from README.md, but every time I get this error:

```
E/flutter (12336): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method login on channel ec.dina/flutter_facebook_auth)
E/flutter (12336): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:7)
E/flutter (12336): <asynchronous suspension>
E/flutter (12336): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
E/flutter (12336): #2      FacebookAuth.login (package:flutter_facebook_auth/flutter_facebook_auth.dart:29:24)
E/flutter (12336): #3      _loginPageState._login (package:+++++/pages/loginPage.dart:55:48)
E/flutter (12336): #4      _loginPageState.build.<anonymous closure> (package:+++++/pages/loginPage.dart:201:33)
E/flutter (12336): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:992:19)
E/flutter (12336): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1098:38)
E/flutter (12336): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
E/flutter (12336): #8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:524:11)
E/flutter (12336): #9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:284:5)
E/flutter (12336): #10     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:256:7)
E/flutter (12336): #11     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:158:27)
E/flutter (12336): #12     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:224:20)
E/flutter (12336): #13     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
E/flutter (12336): #14     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:158:7)
E/flutter (12336): #15     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:104:7)
E/flutter (12336): #16     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:88:7)
E/flutter (12336): #17     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (12336): #18     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (12336): #19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (12336): #20     _invoke1 (dart:ui/hooks.dart:283:10)
E/flutter (12336): #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:192:5)
E/flutter (12336): 
```

I just copied and pasted from the example, I'm not sure what's causing this. Could someone please help me figure this out?

This is my `flutter doctor --verbose`:

```
[√] Flutter (Channel master, 1.20.0-1.0.pre.135, on Microsoft Windows [Version 10.0.18362.900], locale en-US)
    • Flutter version 1.20.0-1.0.pre.135 at C:\src\flutter
    • Framework revision eaf9ff738a (24 hours ago), 2020-06-22 11:53:54 -0700
    • Engine revision 676cd566f7
    • Dart version 2.9.0 (build 2.9.0-17.0.dev 7e72c9ae7e)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\++++\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.46.1)
    • VS Code at C:\Users\++++\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[√] Connected device (4 available)
    • SM G950F   • ce10182a248e403703 • android-arm64  • Android 9 (API 28)
    • Web Server • web-server         • web-javascript • Flutter Tools
    • Chrome     • chrome             • web-javascript • Google Chrome 83.0.4103.116
    • Edge       • edge               • web-javascript • Microsoft Edge 83.0.478.45
```

**Comment by darwin-morocho** [comment]
This error generally occur when you get a plugin and not build the app again. If this is your case after getting the plugin on pubspec.yaml reinstall your apk. If this is not your problem did you created your project with support for swift?

**Comment by juliano0365** [comment]
This solved the login issue, but now there's another one:

```
E/flutter (10475): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(500, SERVER_ERROR: [code] 1675030 [message]: Erreur lors de l’envoi de la requête. [extra]: , null)
E/flutter (10475): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:572:7)
E/flutter (10475): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:161:18)
E/flutter (10475): <asynchronous suspension>
E/flutter (10475): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
E/flutter (10475): #3      FacebookAuth.login (package:flutter_facebook_auth/flutter_facebook_auth.dart:29:24)
E/flutter (10475): #4      _loginPageState._login (package:smarktplacev2/pages/loginPage.dart:55:48)
E/flutter (10475): #5      _loginPageState.build.<anonymous closure> (package:smarktplacev2/pages/loginPage.dart:204:33)
E/flutter (10475): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:992:19)
E/flutter (10475): #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1098:38)
E/flutter (10475): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
E/flutter (10475): #9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:524:11)
E/flutter (10475): #10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:284:5)
E/flutter (10475): #11     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:256:7)
E/flutter (10475): #12     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:158:27)
E/flutter (10475): #13     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:224:20)
E/flutter (10475): #14     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
E/flutter (10475): #15     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:158:7)
E/flutter (10475): #16     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:104:7)
E/flutter (10475): #17     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:88:7)
E/flutter (10475): #18     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (10475): #19     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (10475): #20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (10475): #21     _invoke1 (dart:ui/hooks.dart:283:10)
E/flutter (10475): #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:192:5)
E/flutter (10475): 
```

Btw thanks for the quick response

**Comment by juliano0365** [comment]
This fixed the login issue, but now there's another one:

```
E/flutter (10475): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(500, SERVER_ERROR: [code] 1675030 [message]: Erreur lors de l’envoi de la requête. [extra]: , null)
E/flutter (10475): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:572:7)
E/flutter (10475): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:161:18)
E/flutter (10475): <asynchronous suspension>
E/flutter (10475): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
E/flutter (10475): #3      FacebookAuth.login (package:flutter_facebook_auth/flutter_facebook_auth.dart:29:24)
E/flutter (10475): #4      _loginPageState._login (package:smarktplacev2/pages/loginPage.dart:55:48)
E/flutter (10475): #5      _loginPageState.build.<anonymous closure> (package:smarktplacev2/pages/loginPage.dart:204:33)
E/flutter (10475): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:992:19)
E/flutter (10475): #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1098:38)
E/flutter (10475): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
E/flutter (10475): #9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:524:11)
E/flutter (10475): #10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:284:5)
E/flutter (10475): #11     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:256:7)
E/flutter (10475): #12     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:158:27)
E/flutter (10475): #13     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:224:20)
E/flutter (10475): #14     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
E/flutter (10475): #15     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:158:7)
E/flutter (10475): #16     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:104:7)
E/flutter (10475): #17     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:88:7)
E/flutter (10475): #18     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (10475): #19     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (10475): #20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (10475): #21     _invoke1 (dart:ui/hooks.dart:283:10)
E/flutter (10475): #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:192:5)
E/flutter (10475): 
```

Btw thanks for the quick response

**Comment by darwin-morocho** [comment]
> Erreur lors de l’envoi de la requête.

this error is not linked with flutter_facebook_auth

**Comment by darwin-morocho** [comment]
> This fixed the login issue, but now there's another one:
> 
> ```
> E/flutter (10475): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(500, SERVER_ERROR: [code] 1675030 [message]: Erreur lors de l’envoi de la requête. [extra]: , null)
> E/flutter (10475): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:572:7)
> E/flutter (10475): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:161:18)
> E/flutter (10475): <asynchronous suspension>
> E/flutter (10475): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
> E/flutter (10475): #3      FacebookAuth.login (package:flutter_facebook_auth/flutter_facebook_auth.dart:29:24)
> E/flutter (10475): #4      _loginPageState._login (package:smarktplacev2/pages/loginPage.dart:55:48)
> E/flutter (10475): #5      _loginPageState.build.<anonymous closure> (package:smarktplacev2/pages/loginPage.dart:204:33)
> E/flutter (10475): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:992:19)
> E/flutter (10475): #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1098:38)
> E/flutter (10475): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
> E/flutter (10475): #9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:524:11)
> E/flutter (10475): #10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:284:5)
> E/flutter (10475): #11     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:256:7)
> E/flutter (10475): #12     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:158:27)
> E/flutter (10475): #13     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:224:20)
> E/flutter (10475): #14     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
> E/flutter (10475): #15     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:158:7)
> E/flutter (10475): #16     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:104:7)
> E/flutter (10475): #17     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:88:7)
> E/flutter (10475): #18     _rootRunUnary (dart:async/zone.dart:1206:13)
> E/flutter (10475): #19     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
> E/flutter (10475): #20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
> E/flutter (10475): #21     _invoke1 (dart:ui/hooks.dart:283:10)
> E/flutter (10475): #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:192:5)
> E/flutter (10475): 
> ```
> 
> Btw thanks for the quick response

this error is not linked with flutter_facebook_auth

**Comment by juliano0365** [comment]
You're right. Closing issue...
